(function(name,data){
 if(typeof onTileMapLoaded === 'undefined') {
  if(typeof TileMaps === 'undefined') TileMaps = {};
  TileMaps[name] = data;
 } else {
  onTileMapLoaded(name,data);
 }})("shrine_level",
{ "height":10,
 "layers":[
        {
         "compression":"zlib",
         "data":"eJzTZWBgsANieyB2QGPjArZo6mC0PhCb4tEHAopArATEykCsQkCtOdQuagF7MtxDinuHEkD2FzqNz5+qQKwBxOoU2K2OZI4uFOtTYJ4+1AwDBkj6A2FzqD0aULvU8OiHycPcZQ41wwKIAZNuC10=",
         "encoding":"base64",
         "height":10,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }, 
        {
         "draworder":"topdown",
         "height":10,
         "name":"Colliders",
         "objects":[
                {
                 "height":32,
                 "id":2,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":224,
                 "x":416,
                 "y":0
                }, 
                {
                 "height":96,
                 "id":3,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":0
                }, 
                {
                 "height":96,
                 "id":4,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":96,
                 "x":544,
                 "y":224
                }, 
                {
                 "height":32,
                 "id":5,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":128,
                 "x":416,
                 "y":288
                }, 
                {
                 "height":96,
                 "id":6,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":96,
                 "x":0,
                 "y":224
                }, 
                {
                 "height":32,
                 "id":7,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":128,
                 "x":96,
                 "y":288
                }, 
                {
                 "height":32,
                 "id":8,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":224,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":64,
                 "id":9,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":32
                }, 
                {
                 "height":32,
                 "id":10,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":128,
                 "x":256,
                 "y":32
                }, 
                {
                 "height":32,
                 "id":11,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":128,
                 "x":128,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":12,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":128,
                 "x":384,
                 "y":96
                }, 
                {
                 "height":32,
                 "id":13,
                 "name":"",
                 "properties":
                    {

                    },
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":256,
                 "x":192,
                 "y":192
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":20,
         "x":0,
         "y":0
        }],
 "nextobjectid":14,
 "orientation":"orthogonal",
 "properties":
    {

    },
 "renderorder":"right-up",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"..\/Workspace\/CS194GameDev\/Assets\/Tilemaps\/twilight_tiles.png",
         "imageheight":256,
         "imagewidth":256,
         "margin":0,
         "name":"twilight_tiles",
         "properties":
            {

            },
         "spacing":0,
         "tilecount":64,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":20
});